//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//  xsd.exe pacs.002.spi.1.3.xsd /c /language:CS /namespace:Model
// 
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.7.3081.0.
// 
namespace Model {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.bcb.gov.br/pi/pacs.002/1.3")]
    [System.Xml.Serialization.XmlRootAttribute("Envelope", Namespace="https://www.bcb.gov.br/pi/pacs.002/1.3", IsNullable=false)]
    public partial class SPIEnvelopeMessage {
        
        private SPIhead00100101 appHdrField;
        
        private SPIpacs00200110 documentField;
        
        /// <remarks/>
        public SPIhead00100101 AppHdr {
            get {
                return this.appHdrField;
            }
            set {
                this.appHdrField = value;
            }
        }
        
        /// <remarks/>
        public SPIpacs00200110 Document {
            get {
                return this.documentField;
            }
            set {
                this.documentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="SPI.head.001.001.01", Namespace="https://www.bcb.gov.br/pi/pacs.002/1.3")]
    public partial class SPIhead00100101 {
        
        private Party9Choice frField;
        
        private Party9Choice toField;
        
        private string bizMsgIdrField;
        
        private string msgDefIdrField;
        
        private System.DateTime creDtField;
        
        private System.Xml.XmlElement sgntrField;
        
        /// <remarks/>
        public Party9Choice Fr {
            get {
                return this.frField;
            }
            set {
                this.frField = value;
            }
        }
        
        /// <remarks/>
        public Party9Choice To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        public string BizMsgIdr {
            get {
                return this.bizMsgIdrField;
            }
            set {
                this.bizMsgIdrField = value;
            }
        }
        
        /// <remarks/>
        public string MsgDefIdr {
            get {
                return this.msgDefIdrField;
            }
            set {
                this.msgDefIdrField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreDt {
            get {
                return this.creDtField;
            }
            set {
                this.creDtField = value;
            }
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Sgntr {
            get {
                return this.sgntrField;
            }
            set {
                this.sgntrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.bcb.gov.br/pi/pacs.002/1.3")]
    public partial class Party9Choice {
        
        private BranchAndFinancialInstitutionIdentification5 itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FIId")]
        public BranchAndFinancialInstitutionIdentification5 Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.bcb.gov.br/pi/pacs.002/1.3")]
    public partial class BranchAndFinancialInstitutionIdentification5 {
        
        private FinancialInstitutionIdentification8 finInstnIdField;
        
        /// <remarks/>
        public FinancialInstitutionIdentification8 FinInstnId {
            get {
                return this.finInstnIdField;
            }
            set {
                this.finInstnIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.bcb.gov.br/pi/pacs.002/1.3")]
    public partial class FinancialInstitutionIdentification8 {
        
        private GenericFinancialIdentification1 othrField;
        
        /// <remarks/>
        public GenericFinancialIdentification1 Othr {
            get {
                return this.othrField;
            }
            set {
                this.othrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.bcb.gov.br/pi/pacs.002/1.3")]
    public partial class GenericFinancialIdentification1 {
        
        private string idField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.bcb.gov.br/pi/pacs.002/1.3")]
    public partial class OriginalTransactionReference28 {
        
        private System.DateTime intrBkSttlmDtField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime IntrBkSttlmDt {
            get {
                return this.intrBkSttlmDtField;
            }
            set {
                this.intrBkSttlmDtField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.bcb.gov.br/pi/pacs.002/1.3")]
    public partial class DateAndDateTime2Choice {
        
        private System.DateTime itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DtTm")]
        public System.DateTime Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.bcb.gov.br/pi/pacs.002/1.3")]
    public partial class StatusReason6Choice {
        
        private ExternalStatusReason1Code itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cd")]
        public ExternalStatusReason1Code Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.bcb.gov.br/pi/pacs.002/1.3")]
    public enum ExternalStatusReason1Code {
        
        /// <remarks/>
        AB03,
        
        /// <remarks/>
        AB09,
        
        /// <remarks/>
        AC03,
        
        /// <remarks/>
        AC06,
        
        /// <remarks/>
        AC07,
        
        /// <remarks/>
        AC14,
        
        /// <remarks/>
        AG03,
        
        /// <remarks/>
        AGNT,
        
        /// <remarks/>
        AM01,
        
        /// <remarks/>
        AM04,
        
        /// <remarks/>
        AM09,
        
        /// <remarks/>
        AM18,
        
        /// <remarks/>
        BE01,
        
        /// <remarks/>
        CH11,
        
        /// <remarks/>
        CH16,
        
        /// <remarks/>
        DS04,
        
        /// <remarks/>
        DS0G,
        
        /// <remarks/>
        DT02,
        
        /// <remarks/>
        ED05,
        
        /// <remarks/>
        FF08,
        
        /// <remarks/>
        RC09,
        
        /// <remarks/>
        RC10,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.bcb.gov.br/pi/pacs.002/1.3")]
    public partial class StatusReasonInformation12 {
        
        private StatusReason6Choice rsnField;
        
        private string[] addtlInfField;
        
        /// <remarks/>
        public StatusReason6Choice Rsn {
            get {
                return this.rsnField;
            }
            set {
                this.rsnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AddtlInf")]
        public string[] AddtlInf {
            get {
                return this.addtlInfField;
            }
            set {
                this.addtlInfField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.bcb.gov.br/pi/pacs.002/1.3")]
    public partial class PaymentTransaction110 {
        
        private string orgnlInstrIdField;
        
        private string orgnlEndToEndIdField;
        
        private ExternalPaymentTransactionStatus1Code txStsField;
        
        private StatusReasonInformation12[] stsRsnInfField;
        
        private DateAndDateTime2Choice fctvIntrBkSttlmDtField;
        
        private OriginalTransactionReference28 orgnlTxRefField;
        
        /// <remarks/>
        public string OrgnlInstrId {
            get {
                return this.orgnlInstrIdField;
            }
            set {
                this.orgnlInstrIdField = value;
            }
        }
        
        /// <remarks/>
        public string OrgnlEndToEndId {
            get {
                return this.orgnlEndToEndIdField;
            }
            set {
                this.orgnlEndToEndIdField = value;
            }
        }
        
        /// <remarks/>
        public ExternalPaymentTransactionStatus1Code TxSts {
            get {
                return this.txStsField;
            }
            set {
                this.txStsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StsRsnInf")]
        public StatusReasonInformation12[] StsRsnInf {
            get {
                return this.stsRsnInfField;
            }
            set {
                this.stsRsnInfField = value;
            }
        }
        
        /// <remarks/>
        public DateAndDateTime2Choice FctvIntrBkSttlmDt {
            get {
                return this.fctvIntrBkSttlmDtField;
            }
            set {
                this.fctvIntrBkSttlmDtField = value;
            }
        }
        
        /// <remarks/>
        public OriginalTransactionReference28 OrgnlTxRef {
            get {
                return this.orgnlTxRefField;
            }
            set {
                this.orgnlTxRefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.bcb.gov.br/pi/pacs.002/1.3")]
    public enum ExternalPaymentTransactionStatus1Code {
        
        /// <remarks/>
        ACCC,
        
        /// <remarks/>
        ACSC,
        
        /// <remarks/>
        ACSP,
        
        /// <remarks/>
        RJCT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.bcb.gov.br/pi/pacs.002/1.3")]
    public partial class GroupHeader91 {
        
        private string msgIdField;
        
        private System.DateTime creDtTmField;
        
        /// <remarks/>
        public string MsgId {
            get {
                return this.msgIdField;
            }
            set {
                this.msgIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreDtTm {
            get {
                return this.creDtTmField;
            }
            set {
                this.creDtTmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.bcb.gov.br/pi/pacs.002/1.3")]
    public partial class FIToFIPaymentStatusReportV10 {
        
        private GroupHeader91 grpHdrField;
        
        private PaymentTransaction110[] txInfAndStsField;
        
        /// <remarks/>
        public GroupHeader91 GrpHdr {
            get {
                return this.grpHdrField;
            }
            set {
                this.grpHdrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TxInfAndSts")]
        public PaymentTransaction110[] TxInfAndSts {
            get {
                return this.txInfAndStsField;
            }
            set {
                this.txInfAndStsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="SPI.pacs.002.001.10", Namespace="https://www.bcb.gov.br/pi/pacs.002/1.3")]
    public partial class SPIpacs00200110 {
        
        private FIToFIPaymentStatusReportV10 fIToFIPmtStsRptField;
        
        /// <remarks/>
        public FIToFIPaymentStatusReportV10 FIToFIPmtStsRpt {
            get {
                return this.fIToFIPmtStsRptField;
            }
            set {
                this.fIToFIPmtStsRptField = value;
            }
        }
    }
}
